module.exports = [
	"callback_query",
	"inline_query",
	"chosen_inline_result",
	"channel_post",
	"edited_message",
	"edited_message_text",
	"edited_message_caption",
	"edited_channel_post",
	"edited_channel_post_text",
	"edited_channel_post_caption",
	"shipping_query",
	"pre_checkout_query",
	"poll",
	"polling_error",
	"webhook_error",
	"error",
];
